### ISSUE TITLE
Increase the randomness of the random time

### ISSUE THREAD

**Issue by Haaroon** [InfamyStudio/lostArkAntiAFKBot#1]
The game seems to set you to AFK mode around 30 mins with a popup that states you must click OK to continue.

So i believe settings the timer between events to a random time between 30 seconds - 20 minutes is much more variable and better.

**Comment by InfamyStudio** [comment]
Sound thank you for that, I will make changes to the script on V1.1 - I may even setup user entered time ranges. Have you got any other suggestions or ideas?

**Comment by InfamyStudio** [comment]
V1.1 Being Released Now with all the required updates!

**Comment by Haaroon** [comment]
personally, I would leave the AFK application as a separate tool. 

In your future changelog, you want to add additional features, those can be seen as botting more than just an AFK trigger. 

Next step would be to make a USB physical interface that sends commands directly from the keyboard and mouse, that would be undetectable by the OS and EAC

**Comment by InfamyStudio** [comment]
Yes I see what you mean, undecided whether to leave this as is as this program is also pretty universal and could be effectively set up for any application. Timings have been now user set, and eventually keys to click will be an upcoming change. I am also planning to integrate a cursor cords system which allows you to almost setup the field instead of my system detecting your resolution and scaling the play/click area. 

For the USB interfacing I would need to do some research in how to mimic the program as a keyboard/mouse. For example I own a USB rubber ducky which does just that right and that has its own language so something on the lines of that could be a good idea!
